config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :bookmarks
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists
  validates :title, uniqueness: true,  presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
   @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to lists_path(@list)
  end

  def new
   @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

    def destroy
      @list = List.find(params[:id])
      @list.destroy
      redirect_to lists_path, notice: 'Restaurant was successfully destroyed.', status: :see_other
    end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container pt-4 col-4">
  <h1>Edit List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %> <br>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-success text-white' %>
  <% end %>

  <br>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container pt-5 col-4 banner">
    <h1>All Movie Lists</h1>
    <%= link_to 'Create a list', new_list_path, class: 'btn btn-success text-white', style: 'margin: 10px;' %>
  </div>
</div>

<div class="container pt-5 col-4">
  <div class="card-index">
    <% @lists.each do |list| %>
    <% if list.photo.key %>
      <%=  cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag 'https://res.cloudinary.com/dwoz78u8z/image/upload/v1661513495/kksgxdj5efn7leuvtcs8.jpg', height: 300, width: 400, crop: :fill %>
    <% end %>
    <%= link_to list.name, list_path(list), class: 'btn btn-danger text-white', style: 'margin: 10px;' %> <br>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container pt-4 col-4">
  <h1>Create List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %> <br>
     <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-success text-white' %>
  <% end %>

  <br>

  <%= link_to "Back to lists", lists_path, class: 'btn btn-danger text-white', style: 'margin: 10px;' %>
</div>

app/views/lists/show.html.erb
<div class="container pt-5 col-4">
 <h1 style="font-size: 30px;">Welcome to the <%= @list.name %> movie</h1>
</div>

<div class="container pt-5 col-4">
  <div class="card">
    <% if @list.photo.key %>
      <%= cl_image_tag @list.photo.key %>
    <% else %>
      <%= image_tag 'https://res.cloudinary.com/dwoz78u8z/image/upload/v1661513495/kksgxdj5efn7leuvtcs8.jpg', height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
</div>

<div class="container pt-5 col-4 buttons">
  <%= link_to 'Back on main page', lists_path, class: 'btn btn-success text-white', style: 'margin: 10px;'  %>
  <%= link_to 'Edit the List', edit_list_path, class: 'btn btn-success text-white', style: 'margin: 10px;' %>
  <%= link_to 'Delete the list', @list , data: {  turbo_method: :delete, turbo_confirm: 'Are you sure?' },  class: 'btn btn-success text-white', style: 'margin: 10px;' %>
</div>